site_name: 神秘礼物 · Emby Wiki
site_description: 私有 Emby 使用说明与规则文档
site_author: 神秘礼物

theme:
  name: material
  language: zh

  icon:
    logo: material/gift

  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: 切换到深色模式

    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式

  features:
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.highlight
    - search.suggest
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/smlw22

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: grid
          class: grid
        - name: card
          class: card
  - pymdownx.emoji

nav:
  - 🏠 首页: index.md

  - 📘 使用指南:
      - 使用总览: guide/index.md
      - 💳 公费服说明: guide/paid.md
      - 🌱 公益服说明: guide/public.md

  - ▶️ 客户端与播放:
      - 🎬 客户端与播放说明: client/index.md

  - 🎯 专属抽奖中心:
      - 🎰 活动说明: lottery/index.md

  - ❓ FAQ:
      - 常见问题: faq/index.md

  - 📚 更新与公告:
      - 🎬 视频更新记录: update/index.md

  - 其他:
      - ℹ️ 其他信息: other/index.md
      - ⚠️ 使用声明: statement.md
      - 📢 官方联系: contact/index.md